### ISSUE TITLE
xmpp-js unable to join a MUC from matrix

### ISSUE THREAD

**Issue by sim0nx** [matrix-org/matrix-bifrost#111]
I am trying to join an XMPP MUC:
room name:  test
MUC domain:  con.xmpp.example.com
Matrix domain:  matrix.example.com

So the room name should be:
#_xmpp_con.xmpp.example.com_test:matrix.example.com

if I understand the wiki correctly.

If I try that I only get an error in riot that it is not a valid room name.
Continuing anyway gives an error in the synapse logs (epexted "!" prefix)

The relevant config file part (registration.yaml) is:
```
namespaces:
  users:
    - exclusive: true
      regex: '@_xmpp_.*'
  aliases:
    - exclusive: true
      regex: '#_xmpp_.*'
  rooms: []
```

Any hints would be appreciated.
