### ISSUE TITLE
Document setup process better

### ISSUE THREAD

**Issue by aaptel** [matrix-org/matrix-bifrost#52]
* Do I have to run this on the same machine as the matrix server?
* Does this require an xmpp server?
* Do I have to run this on the same machine as the xmpp server?

I just want to talk to xmpp contacts through my existing xmpp account which is on a free xmpp server I do not own. Is this the software the best way to do that at the moment?

```
  backendOpts: <=== no sure what to put here
     # endpoint to reach the component on. The default port is 5347                                                                                                                                                                          
     service: "xmpp://localhost:5347"
     # domin assigned to the component.                                                                                                                                                                                                      
     domain: "matrix.localhost"
     # password needed by the component.                                                                                                                                                                                                     
     password: "jam"



portals:
  # List of regexes to match a alias that can be turned into a bridge.                                                                                                                                                                       
  aliases:
    # This matches _purple_ followed by anything                                                                                                                                                                                             
    "/^_xmpp_(.+)$/":
      # Use the prpl-jabber protocol.                                                                                                                                                                                                        
      protocol: "prpl-jabber" <===== does this need to be changed for xmpp.js?
      properties:
        # Set room to the first regex match                                                                                                                                                                                                  
        room: "regex:1"
        # Set the server to be conf.localhost                                                                                                                                                                                                
        server: "conf.localhost"
```
