### ISSUE TITLE
XMPP - can't leave room

### ISSUE THREAD

**Issue by licaon-kter** [matrix-org/matrix-bifrost#53]
ejabberd log: https://gist.github.com/9d2601e0acefe836582aa73528f1d785

**Comment by Half-Shot** [comment]
I'm assuming this a gateway bug?

**Comment by jkasun** [comment]
Is this issue is a good first issue to get started?

**Comment by Half-Shot** [comment]
Errrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrm probably not, it's likely to be complicate :(

**Comment by licaon-kter** [comment]
ejabberd blocking the whole bridge server:
```
s2s_access: s2s
acl:
  ...
  blocked_servers:
    server:
      - "bridge.xmpp.matrix.org"

access_rules:
  ...
  s2s:
    - deny: blocked_servers
    - allow
```

But my server log is full of:
```
[info] <0.5903.0>@ejabberd_s2s_in:handle_auth_success:181 (tls|<0.5903.0>) Accepted inbound s2s EXTERNAL authentication bridge.xmpp.matrix.org -> mydomain.tld (hidden_by_ejabberd)
[info] <0.5903.0>@ejabberd_s2s_in:process_closed:131 Closing inbound s2s connection bridge.xmpp.matrix.org -> mydomain.tld: Stream closed by local host: invalid-from
```

And my ghosts are stuck in the room:
![hotelbridgetonia](https://user-images.githubusercontent.com/2282799/54751073-776f8480-4be2-11e9-92d5-1b57f152b2db.jpg)

Fun stuff, the `[cnvrs]` user didn't even manage to actually join, more info here: https://github.com/conversejs/converse.js/issues/1459

@Half-Shot Plenty of commits in the mean time, some sound useful, they are not deployed yet?
